### PR TITLE
Summary:  add Semigroup instance (GHC 8.4 compat)

### LINKED ISSUE #4: Build failure with GHC 8.4.1, due to SMP
```
[nix-shell:~/nanospec]$ cabal build
Resolving dependencies...
Configuring nanospec-0.2.1...
Preprocessing library for nanospec-0.2.1..
Building library for nanospec-0.2.1..
[1 of 1] Compiling Test.Hspec       ( src/Test/Hspec.hs, dist/build/Test/Hspec.o )

src/Test/Hspec.hs:78:10: error:
    • No instance for (Semigroup Summary)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Summary’
   |
78 | instance Monoid Summary where
   |          ^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by deepfire**
This fixes #4, and enables build with GHC 8.4.1.  Also tested on 8.0.2 and 7.10.3.

### CODE REVIEW

**Comment by sol** [comment]
Hey, thanks for your contribution.
